package com.htge.login.model;

import java.io.Serializable;

public class Userinfo implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.id
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.username
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.userdata
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    private String userdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.role
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.id
     *
     * @return the value of USERINFO.id
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.id
     *
     * @param id the value for USERINFO.id
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.username
     *
     * @return the value of USERINFO.username
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.username
     *
     * @param username the value for USERINFO.username
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.userdata
     *
     * @return the value of USERINFO.userdata
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public String getUserdata() {
        return userdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.userdata
     *
     * @param userdata the value for USERINFO.userdata
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public void setUserdata(String userdata) {
        this.userdata = userdata == null ? null : userdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.role
     *
     * @return the value of USERINFO.role
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.role
     *
     * @param role the value for USERINFO.role
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}