spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 1234
  freemarker:
    template-loader-path: ["classpath:/ftl/"]
  datasource:
    name: public
    username: user
    password: Release@
    url: jdbc:mysql://localhost:3306/public?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 0
    password: Release@
security:
  user:
    name: admin
    password: Release@
  basic:
    path: /manage
management:
  security:
    roles: ["ADMIN"]
    enabled: true
  context-path: /manage
server:
  session:
    cookie:
      name: JSESSID
login:
  next-root: http://localhost:8081/dl/
  root-path: http://localhost:8080/auth/
file:
  local-dir: /Users/ge/Desktop
  server-root: /dl/
  authorization: true
  watcher: false