package com.htge.login.model.mapper;

import com.htge.login.model.Userinfo;
import java.util.List;
import java.util.Map;

import com.htge.login.model.UserinfoDaoProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@SuppressWarnings("all")
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Delete({
        "delete from USERINFO",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int deleteByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Insert({
        "insert into USERINFO (username, ",
        "userdata, role)",
        "values (#{username,jdbcType=VARCHAR}, ",
        "#{userdata,jdbcType=VARCHAR}, #{role,jdbcType=INTEGER})"
    })
    int insert(Userinfo record);

    @InsertProvider(type = UserinfoDaoProvider.class, method = "insertList")
    int insertList(List<Userinfo> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Select({
        "select",
        "id, username, userdata, role",
        "from USERINFO",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userdata", property="userdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER)
    })
    Userinfo selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Select({
//            "SELECT * FROM USERINFO WHERE id >= ( SELECT id FROM USERINFO ORDER BY id LIMIT #{arg0,jdbcType=INTEGER}, 1 ) LIMIT #{arg1,jdbcType=INTEGER}"
        "SELECT * FROM USERINFO INNER JOIN",
        "(SELECT id FROM USERINFO order by id LIMIT #{arg0,jdbcType=INTEGER}, #{arg1,jdbcType=INTEGER}) AS T",
        "USING (id)"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userdata", property="userdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER)
    })
    List<Userinfo> select(Long begin, Long limit);

    @Select({
        "SELECT * FROM USERINFO INNER JOIN",
        "(SELECT id FROM USERINFO order by id desc LIMIT #{arg0,jdbcType=INTEGER}, #{arg1,jdbcType=INTEGER}) AS T",
        "USING (id) order by id"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userdata", property="userdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER)
    })
    List<Userinfo> selectFromEnd(Long begin, Long limit);

    @Select({
        "SELECT COUNT(id) AS count FROM USERINFO"
    })
    @Results({
        @Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER)
    })
    List<Map<String, Long>> size();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Update({
        "update USERINFO",
        "set userdata = #{userdata,jdbcType=VARCHAR},",
          "role = #{role,jdbcType=INTEGER}",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int updateByUsername(Userinfo record);
}