package com.htge.login.model.mapper;

import com.htge.login.model.Userinfo;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Delete({
        "delete from USERINFO",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int deleteByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Insert({
        "insert into USERINFO (username, ",
        "userdata, role)",
        "values (#{username,jdbcType=VARCHAR}, ",
        "#{userdata,jdbcType=VARCHAR}, #{role,jdbcType=INTEGER})"
    })
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Select({
        "select",
        "id, username, userdata, role",
        "from USERINFO",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userdata", property="userdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER)
    })
    Userinfo selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Select({
        "select",
        "id, username, userdata, role",
        "from USERINFO",
        "limit #{arg0,jdbcType=INTEGER}, #{arg1,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userdata", property="userdata", jdbcType=JdbcType.VARCHAR),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER)
    })
    List<Userinfo> select(Integer begin, Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Wed May 30 08:55:44 CST 2018
     */
    @Update({
        "update USERINFO",
        "set userdata = #{userdata,jdbcType=VARCHAR},",
          "role = #{role,jdbcType=INTEGER}",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int updateByUsername(Userinfo record);
}